### ISSUE TITLE
textract-demo-cmk.yml does not create

### ISSUE THREAD

**Issue by kiloz** [aws-samples/healthcare-reports-data-extraction-example#2]
Hi @kampanv 

Thank you for making these templates available.  I an new to CloudFormation.  When I try the `textract-demo-cmk.yml` I get the following error.

```
Resource handler returned message: "Policy contains a statement with one or more invalid principals. (Service: Kms, Status Code: 400, Request ID: 592545ae-6880-44e1-8d09-****)" (RequestToken: 3d01b2c7-a23b-bd8b-fdf9-****, HandlerErrorCode: InvalidRequest)
```

## Expected Behavior

The provided templates work.

## Current Behavior

The above error message is generated and the stack is rolled back.

## Reproduction Steps

Attempt to run the template https://github.com/aws-samples/healthcare-reports-data-extraction-example/blob/main/textract-demo-cmk.yaml

Thank you in advance.

**Comment by kampanv** [comment]
Hello @kiloz, The template use two principals - root & Admin. Make sure you have them in your account, if not please edit the principals in the template before you execute it

**Comment by kiloz** [comment]
> Hello @kiloz, The template use two principals - root & Admin. Make sure you have them in your account, if not please edit the principals in the template before you execute it

Hi @kampanv, We are using AWS SSO, with Control Tower, so we do not have those principals.  Can you recommend a path forward?  Do we need to create a service account (principal)?  If so what permissions will it need?
